# Generated by Django 2.1.1 on 2018-10-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EspacioModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitud', models.CharField(max_length=100)),
                ('latitud', models.CharField(max_length=100)),
                ('estado', models.IntegerField()),
                ('tipo_vehiculo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReservaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.CharField(max_length=100)),
                ('fecha_fin', models.CharField(max_length=100)),
                ('espacios', models.ManyToManyField(to='djangoapi.EspacioModel')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_documento', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=150, unique=True)),
                ('edad', models.IntegerField()),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
    ]
