# Generated by Django 2.1.1 on 2018-10-25 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='espaciomodel',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='djangoapi.UsuarioModel'),
        ),
        migrations.AddField(
            model_name='reservamodel',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='djangoapi.UsuarioModel'),
        ),
    ]
