# Generated by Django 2.1.1 on 2018-09-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapi', '0003_auto_20180927_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteReservaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.CharField(max_length=100)),
                ('id_reserva', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EspaResModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_reserva', models.CharField(max_length=100)),
                ('id_espacio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OferenteEspacioModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.CharField(max_length=100)),
                ('id_espacio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_documento', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=150, unique=True)),
                ('edad', models.IntegerField()),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='ClienteModel',
        ),
        migrations.DeleteModel(
            name='OferenteModel',
        ),
        migrations.DeleteModel(
            name='ParqueaderoModel',
        ),
        migrations.RenameField(
            model_name='espaciomodel',
            old_name='tipo_carro',
            new_name='tipo_vehiculo',
        ),
        migrations.RemoveField(
            model_name='reservamodel',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='espaciomodel',
            name='estado',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='espaciomodel',
            name='id_oferente',
            field=models.CharField(default=5, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='espaciomodel',
            name='latititud',
            field=models.CharField(default=245, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='espaciomodel',
            name='longitud',
            field=models.CharField(default=2343, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservamodel',
            name='fecha_fin',
            field=models.CharField(default=20180927, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservamodel',
            name='fecha_inicio',
            field=models.CharField(default=20180910, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservamodel',
            name='id_cliente',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
