# Generated by Django 2.1.3 on 2018-11-15 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapi', '0003_auto_20181115_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcupadoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ParqueaderoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100)),
                ('longitud', models.CharField(max_length=100)),
                ('laitud', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='djangoapi.UsuarioModel')),
            ],
        ),
        migrations.RemoveField(
            model_name='espaciomodel',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='espaciomodel',
            name='longitud',
        ),
        migrations.RemoveField(
            model_name='reservamodel',
            name='espacios',
        ),
        migrations.AddField(
            model_name='espaciomodel',
            name='numero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservamodel',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='djangoapi.UsuarioModel'),
        ),
        migrations.AddField(
            model_name='ocupadomodel',
            name='espacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapi.EspacioModel'),
        ),
        migrations.AddField(
            model_name='ocupadomodel',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapi.ReservaModel'),
        ),
        migrations.AddField(
            model_name='reservamodel',
            name='ocupados',
            field=models.ManyToManyField(through='djangoapi.OcupadoModel', to='djangoapi.EspacioModel'),
        ),
    ]
