# Generated by Django 2.1.3 on 2018-11-15 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapi', '0004_auto_20181115_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parqueaderomodel',
            old_name='laitud',
            new_name='latitud',
        ),
    ]
