# Generated by Django 2.1.3 on 2018-11-15 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapi', '0005_auto_20181115_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='espaciomodel',
            name='parqueadero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='djangoapi.UsuarioModel'),
        ),
    ]
